[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true

# Add remappings here if you wire in more deps.
remappings = [
  "forge-std/=lib/forge-std/src/",
  "v4-core/=lib/v4-core/",
  "v4-periphery/=lib/v4-periphery/",
  "@uniswap/v4-core/=lib/v4-core/",
  "@uniswap/v4-periphery/=lib/v4-periphery/"
]

[lint]
exclude_lints = ["asm-keccak256"]
